[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "dpluspy"
version = "0.0.0"
authors = [
    {name="Nicholas Collier", email="niwicollier@gmail.com"}
]
description = "Demographic inference with H2, a two-locus statistic"
keywords = [
    "population genetics",
    "demographic inference",
    "ancient DNA",
    ]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "scipy>=1.16.3",
    "moments-popgen>=1.5.3",
    "demes>=0.2.3",
    "tskit>=1.0.3",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    ]

[tool.setuptools]
packages = ["dpluspy"]


